/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminNovoRouteImport } from './routes/_authenticated/admin.novo'
import { Route as AuthenticatedAdminAssociacoesIndexRouteImport } from './routes/_authenticated/admin.associacoes.index'
import { Route as AuthenticatedAdminIdIndexRouteImport } from './routes/_authenticated/admin.$id.index'
import { Route as AuthenticatedAdminAssociacoesNovaRouteImport } from './routes/_authenticated/admin.associacoes.nova'
import { Route as AuthenticatedAdminIdEditarRouteImport } from './routes/_authenticated/admin.$id.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNovoRoute = AuthenticatedAdminNovoRouteImport.update({
  id: '/admin/novo',
  path: '/admin/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAssociacoesIndexRoute =
  AuthenticatedAdminAssociacoesIndexRouteImport.update({
    id: '/admin/associacoes/',
    path: '/admin/associacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIdIndexRoute =
  AuthenticatedAdminIdIndexRouteImport.update({
    id: '/admin/$id/',
    path: '/admin/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssociacoesNovaRoute =
  AuthenticatedAdminAssociacoesNovaRouteImport.update({
    id: '/admin/associacoes/nova',
    path: '/admin/associacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIdEditarRoute =
  AuthenticatedAdminIdEditarRouteImport.update({
    id: '/admin/$id/editar',
    path: '/admin/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/$id': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes': typeof AuthenticatedAdminAssociacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/_authenticated/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/_authenticated/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/_authenticated/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/novo'
    | '/admin/'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/$id/'
    | '/admin/associacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/novo'
    | '/admin'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/$id'
    | '/admin/associacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/novo'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$id/editar'
    | '/_authenticated/admin/associacoes/nova'
    | '/_authenticated/admin/$id/'
    | '/_authenticated/admin/associacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/novo': {
      id: '/_authenticated/admin/novo'
      path: '/admin/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AuthenticatedAdminNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/associacoes/': {
      id: '/_authenticated/admin/associacoes/'
      path: '/admin/associacoes'
      fullPath: '/admin/associacoes/'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id/': {
      id: '/_authenticated/admin/$id/'
      path: '/admin/$id'
      fullPath: '/admin/$id/'
      preLoaderRoute: typeof AuthenticatedAdminIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/associacoes/nova': {
      id: '/_authenticated/admin/associacoes/nova'
      path: '/admin/associacoes/nova'
      fullPath: '/admin/associacoes/nova'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id/editar': {
      id: '/_authenticated/admin/$id/editar'
      path: '/admin/$id/editar'
      fullPath: '/admin/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminNovoRoute: typeof AuthenticatedAdminNovoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminIdEditarRoute: typeof AuthenticatedAdminIdEditarRoute
  AuthenticatedAdminAssociacoesNovaRoute: typeof AuthenticatedAdminAssociacoesNovaRoute
  AuthenticatedAdminIdIndexRoute: typeof AuthenticatedAdminIdIndexRoute
  AuthenticatedAdminAssociacoesIndexRoute: typeof AuthenticatedAdminAssociacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminNovoRoute: AuthenticatedAdminNovoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminIdEditarRoute: AuthenticatedAdminIdEditarRoute,
  AuthenticatedAdminAssociacoesNovaRoute:
    AuthenticatedAdminAssociacoesNovaRoute,
  AuthenticatedAdminIdIndexRoute: AuthenticatedAdminIdIndexRoute,
  AuthenticatedAdminAssociacoesIndexRoute:
    AuthenticatedAdminAssociacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
