/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminDiagnosticosRouteImport } from './routes/_authenticated/admin.diagnosticos'
import { Route as AuthenticatedAdminAssociacoesIndexRouteImport } from './routes/_authenticated/admin.associacoes.index'
import { Route as AuthenticatedAdminIdIndexRouteImport } from './routes/_authenticated/admin.$id.index'
import { Route as AuthenticatedAdminUsuariosNovoRouteImport } from './routes/_authenticated/admin.usuarios.novo'
import { Route as AuthenticatedAdminAssociacoesNovaRouteImport } from './routes/_authenticated/admin.associacoes.nova'
import { Route as AuthenticatedAdminIdEditarRouteImport } from './routes/_authenticated/admin.$id.editar'
import { Route as AuthenticatedAdminAssociacoesIdIndexRouteImport } from './routes/_authenticated/admin.associacoes.$id.index'
import { Route as AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport } from './routes/_authenticated/admin.associacoes.$id.diagnostico.novo'
import { Route as AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport } from './routes/_authenticated/admin.associacoes.$id.diagnostico.$assessmentId'
import { Route as AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport } from './routes/_authenticated/admin.associacoes.$id.catadores.novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticosRoute =
  AuthenticatedAdminDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIndexRoute =
  AuthenticatedAdminAssociacoesIndexRouteImport.update({
    id: '/associacoes/',
    path: '/associacoes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdIndexRoute =
  AuthenticatedAdminIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosNovoRoute =
  AuthenticatedAdminUsuariosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminUsuariosRoute,
  } as any)
const AuthenticatedAdminAssociacoesNovaRoute =
  AuthenticatedAdminAssociacoesNovaRouteImport.update({
    id: '/associacoes/nova',
    path: '/associacoes/nova',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdEditarRoute =
  AuthenticatedAdminIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdIndexRoute =
  AuthenticatedAdminAssociacoesIdIndexRouteImport.update({
    id: '/associacoes/$id/',
    path: '/associacoes/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute =
  AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport.update({
    id: '/associacoes/$id/diagnostico/novo',
    path: '/associacoes/$id/diagnostico/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute =
  AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport.update({
    id: '/associacoes/$id/diagnostico/$assessmentId',
    path: '/associacoes/$id/diagnostico/$assessmentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdCatadoresNovoRoute =
  AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport.update({
    id: '/associacoes/$id/catadores/novo',
    path: '/associacoes/$id/catadores/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/admin/associacoes/$id/': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/$id': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/admin/associacoes/$id': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/_authenticated/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/_authenticated/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/_authenticated/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/_authenticated/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/_authenticated/admin/associacoes/$id/': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/_authenticated/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/_authenticated/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/diagnosticos'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/usuarios/novo'
    | '/admin/$id/'
    | '/admin/associacoes/'
    | '/admin/associacoes/$id/'
    | '/admin/associacoes/$id/catadores/novo'
    | '/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/admin/associacoes/$id/diagnostico/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/diagnosticos'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/usuarios/novo'
    | '/admin/$id'
    | '/admin/associacoes'
    | '/admin/associacoes/$id'
    | '/admin/associacoes/$id/catadores/novo'
    | '/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/admin/associacoes/$id/diagnostico/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/diagnosticos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$id/editar'
    | '/_authenticated/admin/associacoes/nova'
    | '/_authenticated/admin/usuarios/novo'
    | '/_authenticated/admin/$id/'
    | '/_authenticated/admin/associacoes/'
    | '/_authenticated/admin/associacoes/$id/'
    | '/_authenticated/admin/associacoes/$id/catadores/novo'
    | '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/_authenticated/admin/associacoes/$id/diagnostico/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnosticos': {
      id: '/_authenticated/admin/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/': {
      id: '/_authenticated/admin/associacoes/'
      path: '/associacoes'
      fullPath: '/admin/associacoes/'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id/': {
      id: '/_authenticated/admin/$id/'
      path: '/$id'
      fullPath: '/admin/$id/'
      preLoaderRoute: typeof AuthenticatedAdminIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios/novo': {
      id: '/_authenticated/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminUsuariosRoute
    }
    '/_authenticated/admin/associacoes/nova': {
      id: '/_authenticated/admin/associacoes/nova'
      path: '/associacoes/nova'
      fullPath: '/admin/associacoes/nova'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesNovaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id/editar': {
      id: '/_authenticated/admin/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/': {
      id: '/_authenticated/admin/associacoes/$id/'
      path: '/associacoes/$id'
      fullPath: '/admin/associacoes/$id/'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/diagnostico/novo': {
      id: '/_authenticated/admin/associacoes/$id/diagnostico/novo'
      path: '/associacoes/$id/diagnostico/novo'
      fullPath: '/admin/associacoes/$id/diagnostico/novo'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId': {
      id: '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId'
      path: '/associacoes/$id/diagnostico/$assessmentId'
      fullPath: '/admin/associacoes/$id/diagnostico/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/catadores/novo': {
      id: '/_authenticated/admin/associacoes/$id/catadores/novo'
      path: '/associacoes/$id/catadores/novo'
      fullPath: '/admin/associacoes/$id/catadores/novo'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminUsuariosRouteChildren {
  AuthenticatedAdminUsuariosNovoRoute: typeof AuthenticatedAdminUsuariosNovoRoute
}

const AuthenticatedAdminUsuariosRouteChildren: AuthenticatedAdminUsuariosRouteChildren =
  {
    AuthenticatedAdminUsuariosNovoRoute: AuthenticatedAdminUsuariosNovoRoute,
  }

const AuthenticatedAdminUsuariosRouteWithChildren =
  AuthenticatedAdminUsuariosRoute._addFileChildren(
    AuthenticatedAdminUsuariosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDiagnosticosRoute: typeof AuthenticatedAdminDiagnosticosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminIdEditarRoute: typeof AuthenticatedAdminIdEditarRoute
  AuthenticatedAdminAssociacoesNovaRoute: typeof AuthenticatedAdminAssociacoesNovaRoute
  AuthenticatedAdminIdIndexRoute: typeof AuthenticatedAdminIdIndexRoute
  AuthenticatedAdminAssociacoesIndexRoute: typeof AuthenticatedAdminAssociacoesIndexRoute
  AuthenticatedAdminAssociacoesIdIndexRoute: typeof AuthenticatedAdminAssociacoesIdIndexRoute
  AuthenticatedAdminAssociacoesIdCatadoresNovoRoute: typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDiagnosticosRoute: AuthenticatedAdminDiagnosticosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminIdEditarRoute: AuthenticatedAdminIdEditarRoute,
  AuthenticatedAdminAssociacoesNovaRoute:
    AuthenticatedAdminAssociacoesNovaRoute,
  AuthenticatedAdminIdIndexRoute: AuthenticatedAdminIdIndexRoute,
  AuthenticatedAdminAssociacoesIndexRoute:
    AuthenticatedAdminAssociacoesIndexRoute,
  AuthenticatedAdminAssociacoesIdIndexRoute:
    AuthenticatedAdminAssociacoesIdIndexRoute,
  AuthenticatedAdminAssociacoesIdCatadoresNovoRoute:
    AuthenticatedAdminAssociacoesIdCatadoresNovoRoute,
  AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute:
    AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute,
  AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute:
    AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
